msfs_version: 1
backends: [
  {
    dir_name: ram,
    bucket_container_name: dev,
    backend_type: RAM,
  },
  {
    dir_name: minio,
    bucket_container_name: dev,
    backend_type: S3,
    S3: {
      region: us-east-1,
      endpoint: "http://minio:9000",
      access_key_id: minioadmin,
      secret_access_key: minioadmin,
    },
  },
  {
    dir_name: ais,
    bucket_container_name: dev,
    backend_type: S3,
    S3: {
      use_config_env: true,
      use_credentials_env: true,
    },
  },
]
