apiVersion: 1

# List of data sources to insert/update
datasources:
  - name: Prometheus
    type: prometheus
    # Unique ID, useful if you need to reference it elsewhere
    uid: prometheus-main
    
    # URL for Prometheus, using the service name defined in docker-compose
    url: http://prometheus:9090 
    
    access: proxy
    isDefault: true # Makes this the default source for new panels
    version: 1
    
    # Optional: If you want to configure it for a specific organization
    # orgId: 1
